### ISSUE TITLE
add attribute #customResourceProvider="font-name.suffix" to each fonts

### ISSUE THREAD

**Issue by inikishev** [JadeVane/Allure#20]
Hi! How do I perform this step? add attribute #customResourceProvider="font-name.suffix" to each fonts

I added `#customResourceProvider=Allure-Icons.woff2` to Allure-Icons.woff2, and `#customResourceProvider=Monaco.ttf` to Monaco.ttf.

I suspect that it was wrong because a lot of the buttons are missing
![{06B1C4F0-687D-4909-9997-D5EA204D3FF9}](https://github.com/user-attachments/assets/a50a2e19-3b89-4786-afd9-fc16f3d7ddba)

**Comment by JadeVane** [comment]
It looks like the icons are displayed correctly so your configuration is fine.

When I designed this theme, it was for my own use. In order to make the interface look cleaner and more refreshing, I hid some unused buttons, so the `a lot of the buttons are missing`  you mentioned should refer to this.

In fact since this theme was released, I seem to have only received feedback once about a certain button being required but not being able to find, which incidentally seemed to be the calendar button, and then I got that button back.

It's a little difficult to restore all the buttons now, mainly because I haven't had much time to concentrate on it recently, because when restoring the buttons, I also have to adapt the icons of the buttons, which takes a lot of time.

So the temporary solution now is that you can post the buttons that you need to use but can't find, and I will find time to add these buttons back in the near future.

These are things I didn't consider at the beginning, and it seems to be causing trouble for you, and I'm sorry for that.

**Comment by inikishev** [comment]
> It looks like the icons are displayed correctly so your configuration is fine.
> 
> When I designed this theme, it was for my own use. In order to make the interface look cleaner and more refreshing, I hid some unused buttons, so the `a lot of the buttons are missing` you mentioned should refer to this.
> 
> In fact since this theme was released, I seem to have only received feedback once about a certain button being required but not being able to find, which incidentally seemed to be the calendar button, and then I got that button back.
> 
> It's a little difficult to restore all the buttons now, mainly because I haven't had much time to concentrate on it recently, because when restoring the buttons, I also have to adapt the icons of the buttons, which takes a lot of time.
> 
> So the temporary solution now is that you can post the buttons that you need to use but can't find, and I will find time to add these buttons back in the near future.
> 
> These are things I didn't consider at the beginning, and it seems to be causing trouble for you, and I'm sorry for that.

I was looking for buttons like note properties and attributes. But I just noticed that they are there at the bottom and I didn't notice them last time and thought I did something wrong when installing. Sorry for the inconvenience!
